spring.application.name=spring-open-ai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

#######open AI config ######################
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-5-nano
spring.ai.openai.chat.options.temperature=1
spring.ai.openai.embedding.options.model=text-embedding-3-small
##################################################

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:~/chatmemory;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=manoj
spring.datasource.password=manoj123

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

spring.docker.compose.stop.command=down

########vector db config ##################
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=mSpringAI


######## MCP Server ###############
spring.ai.mcp.client.stdio.servers-configuration=classpath:mcp-server.json